# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: route_guide.proto for package 'route_guide'

require 'grpc'
require_relative 'route_guide_pb'

module RouteGuide
  module DirectionsService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'route_guide.DirectionsService'

      rpc :direct_it, ::RouteGuide::DirectionsRequest, ::RouteGuide::DirectionsResponse
    end

    Stub = Service.rpc_stub_class
  end
end
