# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: route_guide.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("route_guide.proto", :syntax => :proto3) do
    add_message "route_guide.DirectionsRequest" do
      optional :current_location, :string, 1
      optional :target_location, :string, 2
      optional :means_of_travel, :string, 3
    end
    add_message "route_guide.DirectionsResponse" do
      optional :directions, :string, 1
      optional :approximate_time_of_travel_in_hrs, :int32, 2
      optional :approximate_distance_in_kms, :int32, 3
    end
  end
end

module RouteGuide
  DirectionsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("route_guide.DirectionsRequest").msgclass
  DirectionsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("route_guide.DirectionsResponse").msgclass
end
